from collections.abc import Callable as Callable
from dataclasses import dataclass
from typing import ParamSpec, TypeVar

from _typeshed import Incomplete
from flext_core import FlextEntity as FlextCliEntity, FlextResult

from flext_ldap.constants import (
    FlextLdapDefaultValues as FlextLdapDefaultValues,
    FlextLdapScope as FlextLdapScope,
)
from flext_ldap.infrastructure import FlextLdapClient as FlextLdapClient
from flext_ldap.models import (
    FlextLdapDistinguishedName as FlextLdapDistinguishedName,
    FlextLdapFilter as FlextLdapFilter,
)

logger: Incomplete
console: Incomplete

@dataclass
class LDAPConnectionParams:
    server: str
    port: int = ...
    use_ssl: bool = ...
    bind_dn: str | None = ...
    bind_password: str | None = ...
    @classmethod
    def from_click_args(
        cls, server: str, port: int, **kwargs: object
    ) -> LDAPConnectionParams: ...

@dataclass
class LDAPSearchParams:
    server: str
    base_dn: str
    filter_str: str = ...
    port: int = ...
    use_ssl: bool = ...
    bind_dn: str | None = ...
    bind_password: str | None = ...
    limit: int = ...
    @classmethod
    def from_click_args(
        cls, server: str, base_dn: str, filter_str: str, **kwargs: object
    ) -> LDAPSearchParams: ...

class _CliPrintMixin:
    def flext_cli_print_info(self, message: str) -> None: ...
    def flext_cli_print_success(self, message: str) -> None: ...
    def flext_cli_print_error(self, message: str) -> None: ...
    def flext_cli_print_warning(self, message: str) -> None: ...

class FlextLdapCliBase(FlextCliEntity, _CliPrintMixin):
    command_id: Incomplete
    def __init__(self, command_id: str, name: str) -> None: ...

class FlextLdapTestCommand(FlextLdapCliBase):
    name: Incomplete
    params: Incomplete
    def __init__(
        self, command_id: str, name: str, params: LDAPConnectionParams
    ) -> None: ...
    def validate_business_rules(self) -> FlextResult[None]: ...
    def execute(self) -> FlextResult[object]: ...

class FlextLdapSearchCommand(FlextLdapCliBase):
    name: Incomplete
    params: Incomplete
    def __init__(
        self, command_id: str, name: str, params: LDAPSearchParams
    ) -> None: ...
    def validate_business_rules(self) -> FlextResult[None]: ...
    def execute(self) -> FlextResult[object]: ...

class FlextLdapUserInfoCommand(FlextLdapCliBase):
    name: Incomplete
    uid: Incomplete
    server: Incomplete
    def __init__(
        self, command_id: str, name: str, uid: str, server: str | None = None
    ) -> None: ...
    def validate_business_rules(self) -> FlextResult[None]: ...
    def execute(self) -> FlextResult[object]: ...

_P = ParamSpec("_P")
_R = TypeVar("_R")

def ldap_connection_options[**P, R](func: Callable[_P, _R]) -> Callable[_P, _R]: ...
def cli() -> None: ...
@ldap_connection_options
def test(
    server: str, port: int, *, ssl: bool, bind_dn: str | None, bind_password: str | None
) -> None: ...
@ldap_connection_options
def search(
    server: str, base_dn: str, filter_str: str, limit: int, **kwargs: object
) -> None: ...
def user_info(uid: str, server: str | None) -> None: ...
def version() -> None: ...
def main() -> None: ...
