from flext_ldap.api import FlextLdapApi
from flext_ldap.config import FlextLdapAuthConfig as FlextLdapConfig
from flext_ldap.exceptions import (
    FlextLdapAuthenticationError,
    FlextLdapConnectionError,
    FlextLdapException,
    FlextLdapSearchError,
)
from flext_ldap.models import FlextLdapEntry, FlextLdapGroup, FlextLdapUser

__all__ = [
    "AuthenticationError",
    "ConnectionError",
    "LDAPClient",
    "LDAPConfig",
    "LDAPEntry",
    "LDAPException",
    "LDAPGroup",
    "LDAPUser",
    "LdapClient",
    "LdapConfig",
    "LdapEntry",
    "LdapException",
    "LdapGroup",
    "LdapUser",
    "SearchError",
    "create_ldap_client",
    "get_ldap_client",
]

def LDAPClient(*args: object, **kwargs: object) -> FlextLdapApi: ...
def LdapClient(*args: object, **kwargs: object) -> FlextLdapApi: ...
def LDAPConfig(*args: object, **kwargs: object) -> FlextLdapConfig: ...
def LdapConfig(*args: object, **kwargs: object) -> FlextLdapConfig: ...
def LDAPUser(*args: object, **kwargs: object) -> FlextLdapUser: ...
def LdapUser(*args: object, **kwargs: object) -> FlextLdapUser: ...
def LDAPGroup(*args: object, **kwargs: object) -> FlextLdapGroup: ...
def LdapGroup(*args: object, **kwargs: object) -> FlextLdapGroup: ...
def LDAPEntry(*args: object, **kwargs: object) -> FlextLdapEntry: ...
def LdapEntry(*args: object, **kwargs: object) -> FlextLdapEntry: ...
def LDAPException(*args: object, **kwargs: object) -> FlextLdapException: ...
def LdapException(*args: object, **kwargs: object) -> FlextLdapException: ...
def ConnectionError(*args: object, **kwargs: object) -> FlextLdapConnectionError: ...
def AuthenticationError(
    *args: object, **kwargs: object
) -> FlextLdapAuthenticationError: ...
def SearchError(*args: object, **kwargs: object) -> FlextLdapSearchError: ...
def get_ldap_client(*args: object, **kwargs: object) -> FlextLdapApi: ...
def create_ldap_client(*args: object, **kwargs: object) -> FlextLdapApi: ...
