from typing import TypeGuard

from flext_ldap.types import (
    TLdapAttributes,
    TLdapAttributeValue,
    TLdapEntryData,
    TLdapSearchResult,
)

__all__ = [
    "ensure_ldap_dn",
    "ensure_string_list",
    "has_error_attribute",
    "has_is_success_attribute",
    "is_bytes_list",
    "is_connection_result",
    "is_ldap_attribute_value",
    "is_ldap_attributes_dict",
    "is_ldap_dn",
    "is_ldap_entry_data",
    "is_ldap_search_result",
    "is_string_list",
]

def is_ldap_dn(value: object) -> TypeGuard[str]: ...
def is_ldap_attribute_value(value: object) -> TypeGuard[TLdapAttributeValue]: ...
def is_ldap_attributes_dict(value: object) -> TypeGuard[TLdapAttributes]: ...
def is_ldap_search_result(value: object) -> TypeGuard[TLdapSearchResult]: ...
def is_ldap_entry_data(value: object) -> TypeGuard[TLdapEntryData]: ...
def is_connection_result(value: object) -> TypeGuard[dict[str, object]]: ...
def is_string_list(value: object) -> TypeGuard[list[str]]: ...
def is_bytes_list(value: object) -> TypeGuard[list[bytes]]: ...
def ensure_string_list(value: str | list[str]) -> list[str]: ...
def ensure_ldap_dn(value: object) -> str: ...
def has_error_attribute(obj: object) -> TypeGuard[object]: ...
def has_is_success_attribute(obj: object) -> TypeGuard[object]: ...
