from flext_ldap.types import LdapAttributeDict as UtilsLdapAttributeDict

__all__ = [
    "FlextLdapErrorHelpers",
    "FlextLdapPerformanceHelpers",
    "FlextLdapUtils",
    "FlextLdapValidationHelpers",
    "LdapAttributeDict",
    "UtilsLdapAttributeDict",
    "flext_ldap_sanitize_attribute_name",
    "flext_ldap_validate_attribute_name",
    "flext_ldap_validate_attribute_value",
    "flext_ldap_validate_dn",
]

class FlextLdapPerformanceHelpers:
    @classmethod
    def cache_config(cls, key: str, config: object) -> None: ...
    @classmethod
    def get_cached_config(cls, key: str) -> object | None: ...
    @classmethod
    def cache_validation_result(
        cls, value: str, validation_type: str, *, result: bool
    ) -> None: ...
    @classmethod
    def get_cached_validation(cls, value: str, validation_type: str) -> bool | None: ...
    @classmethod
    def clear_cache(cls) -> None: ...
    @staticmethod
    def optimize_attribute_processing(
        attributes: dict[str, object],
    ) -> dict[str, object]: ...

class FlextLdapUtils:
    @staticmethod
    def validate_dn(dn: str) -> bool: ...
    @staticmethod
    def validate_attribute_name(name: str) -> bool: ...
    @staticmethod
    def validate_attribute_value(value: object) -> bool: ...
    @staticmethod
    def sanitize_attribute_name(name: str) -> str: ...

class FlextLdapValidationHelpers:
    @staticmethod
    def validate_non_empty_string(value: str, field_name: str) -> str: ...
    @staticmethod
    def validate_dn_field(value: str) -> str: ...
    @staticmethod
    def validate_filter_field(value: str) -> str: ...
    @staticmethod
    def validate_cn_field(value: str) -> str: ...
    @staticmethod
    def validate_file_path_field(value: str) -> str: ...
    @staticmethod
    def validate_uri_field(value: str) -> str: ...
    @staticmethod
    def validate_base_dn_field(value: str) -> str: ...

class FlextLdapErrorHelpers:
    @staticmethod
    def connection_failed_error(error: str | None = None, context: str = "") -> str: ...
    @staticmethod
    def operation_failed_error(operation: str, error: str | None = None) -> str: ...
    @staticmethod
    def validation_failed_error(field: str, reason: str | None = None) -> str: ...

def flext_ldap_validate_dn(dn: str) -> bool: ...
def flext_ldap_validate_attribute_name(name: str) -> bool: ...
def flext_ldap_validate_attribute_value(value: object) -> bool: ...
def flext_ldap_sanitize_attribute_name(name: str) -> str: ...

LdapAttributeDict = UtilsLdapAttributeDict
