import pytest

class TestFlextLdapApiIntegration:
    def test_api_instantiation(self) -> None: ...
    def test_get_ldap_api_singleton(self) -> None: ...
    def test_api_with_config(self) -> None: ...
    @pytest.mark.asyncio
    async def test_connection_lifecycle(self) -> None: ...
    def test_api_flext_core_integration(self) -> None: ...

class TestFlextLdapApiEntityOperations:
    @pytest.mark.asyncio
    async def test_user_creation_flow(self) -> None: ...
    def test_entity_domain_rules(self) -> None: ...

class TestFlextLdapApiE2E:
    @pytest.mark.asyncio
    async def test_complete_user_lifecycle(self) -> None: ...
    @pytest.mark.asyncio
    async def test_group_management_workflow(self) -> None: ...
