HTTP_OK: int
EXPECTED_BULK_SIZE: int
EXPECTED_DATA_COUNT: int

class TestFlextLdapConstants:
    def test_constants_values(self) -> None: ...

class TestFlextLdapConnectionConfig:
    def test_connection_config_defaults(self) -> None: ...
    def test_connection_config_custom(self) -> None: ...
    def test_server_validation_valid(self) -> None: ...
    def test_server_validation_invalid(self) -> None: ...
    def test_port_validation_valid(self) -> None: ...
    def test_port_validation_invalid(self) -> None: ...
    def test_domain_rules_validation_success(self) -> None: ...

class TestFlextLdapAuthConfig:
    def test_auth_config_defaults(self) -> None: ...
    def test_auth_config_custom(self) -> None: ...
    def test_bind_dn_validation(self) -> None: ...
    def test_domain_rules_validation_anonymous_bind(self) -> None: ...
    def test_domain_rules_validation_bind_dn_required(self) -> None: ...
    def test_domain_rules_validation_password_required(self) -> None: ...

class TestFlextLdapSearchConfig:
    def test_search_config_defaults(self) -> None: ...
    def test_search_config_custom(self) -> None: ...

class TestFlextLdapLoggingConfig:
    def test_logging_config_defaults(self) -> None: ...
    def test_logging_config_custom(self) -> None: ...

class TestFlextLdapSettings:
    def test_settings_import(self) -> None: ...
    def test_settings_instantiation_defaults(self) -> None: ...
    def test_settings_custom_values(self) -> None: ...
    def test_get_effective_connection(self) -> None: ...

class TestFlextLdapConfigFactories:
    def test_create_development_config(self) -> None: ...
    def test_create_production_config(self) -> None: ...
    def test_create_test_config(self) -> None: ...
    def test_factory_functions_return_different_instances(self) -> None: ...

class TestFlextLdapConfigIntegration:
    def test_connection_config_full_validation(self) -> None: ...
    def test_auth_config_full_validation(self) -> None: ...
    def test_search_config_limits_validation(self) -> None: ...
    def test_integrated_settings_workflow(self) -> None: ...
