class TestFlextLdapDistinguishedName:
    def test_dn_creation(self) -> None: ...
    def test_dn_factory_method_success(self) -> None: ...
    def test_dn_factory_method_with_empty_string(self) -> None: ...
    def test_dn_equality(self) -> None: ...
    def test_dn_string_representation(self) -> None: ...

class TestFlextLdapFilter:
    def test_filter_creation(self) -> None: ...
    def test_filter_factory_method_success(self) -> None: ...
    def test_filter_complex_filter(self) -> None: ...
    def test_filter_equality(self) -> None: ...

class TestFlextLdapUser:
    def test_user_creation(self) -> None: ...
    def test_user_is_active_default(self) -> None: ...
    def test_user_lock_account(self) -> None: ...
    def test_user_unlock_account(self) -> None: ...
    def test_user_immutability(self) -> None: ...

class TestFlextLdapGroup:
    def test_group_creation(self) -> None: ...
    def test_group_add_member(self) -> None: ...
    def test_group_remove_member(self) -> None: ...
    def test_group_has_member(self) -> None: ...
    def test_group_immutability(self) -> None: ...

class TestFlextLdapEntry:
    def test_entry_creation(self) -> None: ...
    def test_entry_get_attribute(self) -> None: ...
    def test_entry_has_attribute(self) -> None: ...

class TestFlextLdapCreateUserRequest:
    def test_create_user_request_basic(self) -> None: ...
    def test_create_user_request_with_optional_fields(self) -> None: ...
    def test_create_user_request_to_attributes(self) -> None: ...

class TestModelValidation:
    def test_user_dn_validation(self) -> None: ...
    def test_group_member_dn_validation(self) -> None: ...
    def test_create_user_request_validation(self) -> None: ...
