from flext_ldap import (
    TLdapDn as TLdapDn,
    TLdapFilter as TLdapFilter,
    TLdapUri as TLdapUri,
)

class TestLdapTypes:
    def test_ldap_attribute_value_types(self) -> None: ...
    def test_ldap_attribute_dict(self) -> None: ...
    def test_ldap_search_result(self) -> None: ...
    def test_type_aliases(self) -> None: ...

class TestProtocols:
    def test_connection_protocol_structure(self) -> None: ...
    def test_directory_entry_protocol_structure(self) -> None: ...

class TestTypeCompatibility:
    def test_ldap_types_are_importable(self) -> None: ...
    def test_backwards_compatibility(self) -> None: ...
