import pytest

class TestLdapE2EOperations:
    @pytest.mark.asyncio
    async def test_complete_user_lifecycle(self) -> None: ...
    @pytest.mark.asyncio
    async def test_search_operations_flow(self) -> None: ...
    @pytest.mark.asyncio
    async def test_group_management_flow(self) -> None: ...
    @pytest.mark.asyncio
    async def test_connection_error_handling(self) -> None: ...
    def test_api_configuration_integration(self) -> None: ...
    @pytest.mark.asyncio
    async def test_error_propagation_e2e(self) -> None: ...

class TestLdapE2EWithDockerServer:
    @pytest.mark.asyncio
    async def test_real_ldap_user_operations(self) -> None: ...
    @pytest.mark.asyncio
    async def test_real_ldap_search_operations(self) -> None: ...
    @pytest.mark.asyncio
    async def test_real_ldap_group_operations(self) -> None: ...
