from collections.abc import AsyncIterator
from contextlib import asynccontextmanager

from _typeshed import Incomplete

from flext_ldap import FlextLdapApi

logger: Incomplete

@asynccontextmanager
async def ldap_session(
    server_url: str, bind_dn: str | None = None, password: str | None = None
) -> AsyncIterator[tuple[FlextLdapApi, str]]: ...
async def demonstrate_value_objects() -> None: ...
async def demonstrate_comprehensive_configuration() -> None: ...
async def demonstrate_async_patterns() -> None: ...
async def demonstrate_error_recovery() -> None: ...
async def demonstrate_performance_patterns() -> None: ...
async def main() -> None: ...
