from typing import Final

from _typeshed import Incomplete

from flext_ldap import FlextLdapApi

logger: Incomplete

class DockerLDAPContainer:
    container_name: str
    port: Final[int]
    def __init__(self) -> None: ...
    def start_container(self) -> None: ...
    def stop_container(self) -> None: ...

async def demonstrate_complete_crud_operations() -> None: ...
async def perform_create_groups(
    ldap_service: FlextLdapApi, session_id: str
) -> None: ...
async def perform_create_users(ldap_service: FlextLdapApi, session_id: str) -> None: ...
async def perform_read_operations(
    ldap_service: FlextLdapApi, session_id: str
) -> None: ...
async def perform_update_operations(
    ldap_service: FlextLdapApi, session_id: str
) -> None: ...
async def perform_delete_operations(
    ldap_service: FlextLdapApi, session_id: str
) -> None: ...
async def main() -> None: ...
