from _typeshed import Incomplete

logger: Incomplete

def start_openldap_container() -> bool: ...
def stop_openldap_container() -> None: ...
async def run_examples_with_docker() -> None: ...
async def main() -> None: ...
